In [1]:
import pyterrier as pt
import ir_datasets


dataset = ir_datasets.load("argsme/2020-04-01/touche-2020-task-1")

def find_doc(docid):
    for doc in dataset.docs_iter():
        # print(doc)
        # break
        if doc.doc_id == docid:
            return doc
        
find_doc("Sf9294c83-Af186e851")

KeyboardInterrupt:

In [2]:
import json
import pandas as pd

lines = []
with open(r'datasets/kid-friend-en/docs.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
df_final = pd.DataFrame(line_dicts)
df_final.drop_duplicates(inplace=True,ignore_index=True)
df_final.head(1)

,docno,snippet,title,main_content
0,6e421f1539b1457b853712d81be87743,WEBBTS (also Bangtan Boys; Korean: 방탄소년단 Bangt...,BTS (band) - Wikipedia,BTS (also Bangtan Boys; Korean: 방탄소년단 Bangtan ...

In [ ]:
print("Number of documents: ", len(df_final))
print("Longest document length (in characters): ", max([len(text) for text in df_final["main_content"]]))
print("Longest length of document title (in characters): ", max([len(title) for title in df_final["title"]]))
print("Maximum length of doc id (in characters): ", max([len(docno) for docno in df_final["docno"]]))

Number of documents:  2385
Longest document length (in characters):  117554
Longest length of document title (in characters):  452
Maximum length of doc id (in characters):  32

In [ ]:
from pathlib import Path
import pyterrier as pt
import pandas as pd

# df_final.to_dict(orient="records")

idx_path = Path.cwd() / "index" / "kid-friend-en"
indexer = pt.IterDictIndexer(
    index_path = str(idx_path),
    meta={ # metadata recorded in index
        "docno": max([len(docno) for docno in df_final["docno"]]),
        "title": max([len(title) for title in df_final["title"]]),
        "snippet": max([len(snippet) for snippet in df_final["snippet"]]),
        "text": max([len(main_content) for main_content in df_final["main_content"]])
    },
    text_attrs = ["text"], # columns indexed
    stemmer="porter",
    stopwords="terrier",
)

Java started (triggered by TerrierIndexer.__init__) and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]

In [ ]:
def iter():
    for i, row in df_final.iterrows():
        yield {
            "docno": row["docno"],
            "title": row["title"],
            "snippet": row["snippet"],
            "text": row["main_content"]
        }

In [ ]:
index_ref = indexer.index(iter())

08:53:23.014 [main] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (37d53c33110a4231807e71e377f08377) - further warnings are suppressed
08:53:39.246 [main] WARN org.terrier.structures.indexing.Indexer -- Indexed 187 empty documents

In [ ]:
len(df_final.loc[df_final["main_content"]==""])

187

In [ ]:
idx_path = Path.cwd() / "index" / "kid-friend-en"
index = pt.IndexFactory.of(str(idx_path))

In [ ]:
tf_idf = pt.terrier.Retriever(index, wmodel="TF_IDF")

In [ ]:
page = 1
rpp = 10

items = tf_idf.search("bts")['docno'][page*rpp:(page+1)*rpp].tolist()
for i in items: 
    item = df_final.loc[df_final["docno"]==i]
    print({
        'title': item["title"].values[0],
        'snippet': item["snippet"].values[0]
    })

{'title': 'Which Bts Member Is Your Bias Quizzes | Quotev', 'snippet': 'Answer a set of questions to see which BTS member you are most like! Im sorry if this isnt your bias, this is just a comparison. ♡ Share your results!'}
{'title': 'BTS (band) - Wikipedia', 'snippet': 'BTS (also Bangtan Boys; Korean: 방탄소년단 Bangtan Sonyeondan) is a South Korean boy band of the third K-pop generation, consisting of seven ...'}
{'title': 'BTS | Spotify', 'snippet': 'Listen to BTS on Spotify. Artist - 26.6M monthly listeners. Preview of Spotify. Sign up to get unlimited songs and podcasts with occasional ads.'}
{'title': 'BTS - Wikipedia', 'snippet': 'BTS (Korean: 방탄소년단; RR: Bangtan Sonyeondan; lit. Bulletproof Boy Scouts), also known as the Bangtan Boys, is a South Korean boy band formed in 2010. The band consists of Jin, Suga, J-Hope, RM, Jimin, V, and Jungkook, who co-write or co-produce much of their material.Originally a hip hop group, they expanded their musical style to incorporate a wide range of genres, while their lyrics ...'}
{'title': 'BTS | Seitenstark', 'snippet': "Apr 12, 2021 -\nBTS\nEntry by tierfreundin in ...\nHey,\nI've recently become a BTS fan and was wondering if there are any more BTS fans here? I'm happy if a few get in touch and we can talk about them here."}
{'title': 'BTS Bias Quiz: Is He Your Perfect Boyfriend? | Quizzboom', 'snippet': 'Park Jimin was the last to join BTS. "Cute cheeks" is an affectionate and extroverted member who loves spending time with his friends. Despite his friendliness, he has some wicked sense of humor. Fans like to admire his impressive abs as well. Nice and hardworking, according to other boys.'}
{'title': 'BTS official (@bts.bighitofficial) - Instagram photos and videos', 'snippet': '75M Followers, 11 Following, 1,569 Posts - BTS official (@bts.bighitofficial) on Instagram: "#방탄소년단 공식 인스타그램입니다. This is the official Instagram for #BTS #지민 #Jimin \'MUSE\' OUT NOW"'}
{'title': '방탄소년단 - 나무위키', 'snippet': '방탄소년단을 키워낸 빅히트 뮤직 ( HYBE )은 이러한 성과로 국내 4대 대형 기획사 가 되었다. 방탄소년단은 해외를 염두에 두고 기획된 아이돌 그룹이 아닌데도 불구하고 [17] 2017년부터 유튜브 나 빌보드, 스포티파이, 아이튠즈, UK 차트, 오리콘 등 해외 인기 관련 ...'}
{'title': 'BTS Members Profile (Updated!) - Kpop Profiles', 'snippet': 'Learn about BTS (Bangtan Boys), a South Korean boy group with 7 members: RM, Jin, Suga, J-Hope, Jimin, V and Jung Kook. Find out their birthdays, positions, hobbies, ideal types, solo activities and more.'}
{'title': '', 'snippet': ''}

In [28]:
import pandas as pd
import re

commonlit = pd.read_excel("datasets/CLEAR Corpus 6.01.xlsx")
commonlit = commonlit[["ID", "Title", "Excerpt", "Author", "URL", "Source"]]

commonlit["Title"] = commonlit["Title"].apply(lambda x: re.sub(r"(\n+\s*)|(\s+)", " ", x.strip()))
commonlit["Excerpt"] = commonlit["Excerpt"].apply(lambda x: re.sub(r"(\n+\s*)|(\s+)", " ", x.strip()))
commonlit["ID"] = commonlit["ID"].apply(lambda x: str(x))

commonlit = commonlit.rename({"Title": "title", "Excerpt": "snippet", "Source": "source", "Author": "author", "ID": "docno", "URL": "url"}, axis=1)

In [29]:
commonlit.head()

,docno,title,snippet,author,url,source
0,400,Patty's Suitors,When the young people returned to the ballroom...,Carolyn Wells,http://www.gutenberg.org/cache/epub/5631/pg563...,gutenberg
1,401,Two Little Women on a Holiday,"All through dinner time, Mrs. Fayre was somewh...",Carolyn Wells,http://www.gutenberg.org/cache/epub/5893/pg589...,gutenberg
2,402,Patty Blossom,"As Roger had predicted, the snow departed as q...",Carolyn Wells,http://www.gutenberg.org/cache/epub/20945/pg20...,gutenberg
3,403,THE WATER-BABIES A Fairy Tale for a Land-Baby,Mr. Grimes was to come up next morning to Sir ...,CHARLES KINGSLEY,http://www.gutenberg.org/files/25564/25564-h/2...,gutenberg
4,404,HOW THE ARGONAUTS WERE DRIVEN INTO THE UNKNOWN...,And outside before the palace a great garden w...,Charles Kingsley,http://www.gutenberg.org/files/677/677-h/677-h...,gutenberg

In [30]:
commonlit.to_json("datasets/commonlit/docs.jsonl", orient="records", lines=True)

In [31]:
import json
import pandas as pd

lines = []
with open(r'datasets/commonlit/docs.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
df_final = pd.DataFrame(line_dicts)
df_final.drop_duplicates(inplace=True,ignore_index=True)
df_final.head(1)

,docno,title,snippet,author,url,source
0,400,Patty's Suitors,When the young people returned to the ballroom...,Carolyn Wells,http://www.gutenberg.org/cache/epub/5631/pg563...,gutenberg

In [32]:
from pathlib import Path
import pyterrier as pt
import pandas as pd

# df_final.to_dict(orient="records")

idx_path = Path.cwd() / "index" / "commonlit"
indexer = pt.IterDictIndexer(
    index_path = str(idx_path),
    meta={ # metadata recorded in index
        "docno": max([len(docno) for docno in df_final["docno"]]),
        "title": max([len(title) for title in df_final["title"]]),
        "snippet": max([len(snippet) for snippet in df_final["snippet"]]),
        "author": max([len(author) for author in df_final["author"]]),
        "url": max([len(url) for url in df_final["url"]]),
        "source": max([len(source) for source in df_final["source"]])
    },
    text_attrs = ["snippet"], # columns indexed
    stemmer="porter",
    stopwords="terrier",
)

Java started (triggered by TerrierIndexer.__init__) and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]

In [33]:
def iter():
    for i, row in df_final.iterrows():
        yield {
            "docno": row["docno"],
            "title": row["title"],
            "snippet": row["snippet"],
            "author": row["author"],
            "url": row["url"],
            "source": row["source"]
        }

In [34]:
index_ref = indexer.index(iter())

In [35]:
idx_path = Path.cwd() / "index" / "commonlit"
index = pt.IndexFactory.of(str(idx_path))

In [36]:
tf_idf = pt.terrier.Retriever(index, wmodel="TF_IDF")
page = 1
rpp = 10

items = tf_idf.search("boat")['docno'][page*rpp:(page+1)*rpp].tolist()
for i in items: 
    item = df_final.loc[df_final["docno"]==i]
    print({
        'title': item["title"].values[0],
        'snippet': item["snippet"].values[0]
    })

{'title': 'DOWN THE RIVER AFTER THE BOY', 'snippet': 'So he got into the boat, and began to rock it. The boat got loose, and drifted down the river. Walter did not notice this until he was quite a distance from the shore; then, turning round, he saw what had happened. Every moment the current was carrying him further from home. Walter was not a timid boy, and, instead of crying, he began to reason in this way: "The boat does not leak. It is safe and sound. There are no waves to make me afraid. The wind does not blow. Here on a seat is a thick blanket. In this box is a loaf of bread and a knife. The water of the river is good to drink, and here is a tin mug. I think I will not cry, but hope for the best." So he sat down. He called to some people on the shore; but they did not hear him. He stood up, and waved his hat to a man in a passing boat, and cried, "Help, help!" But the man thought it was some little fellow making fun of him.'}
{'title': 'THE LITTLE SAILOR', 'snippet': 'We had a merry party, and our little boy was so full of play, that he dragged the boat-broom in the wake of the boat. Then he tried to stand on the forward-deck, and hold on by the mast. But the wind shifted a little, and the sail turned about so suddenly, that it came near pushing him into the water. So papa ordered him into the stern, where the ladies were, and gave him permission to take hold of the tiller, and help steer the boat. He helped turn her toward the jetty which the government is building to make the water deeper, so that large ships may sail safely into the harbor. Just as we made the turn, we saw another boat coming towards us. The tide was driving it swiftly along, and it bobbed up and down on the sparkling ripples. A little chap was standing on the bow, drying his wet bare legs in the sunshine. He seemed to be enjoying himself hugely, and paid no attention to our party.'}
{'title': '"The Man o\' War\'s \'Er \'Usband"', 'snippet': 'Our drill, that provided for lowering the boats with only half-complements in them, will not serve. We pass orders to lower away in any condition, however overcrowded. The way is off the ship, and it is with some apprehension we watch the packed boats that drop away from the davit heads. The shrill ring of the block-sheaves indicates a tension that is not far from breaking-point. Many of the life-boats reach the water safely with their heavy burdens, but the strain on the tackles — far beyond their working load — is too great for all to stand to it. Two boats go down by the run. The men in them are thrown violently to the water, where they float in the wash and shattered planking. A third dangles from the after fall, having shot her manning out at parting of the forward tackle. Lowered by the stern, she rights, disengages, and drifts aft with the men clinging to the life-lines. We can make no attempt to reach the men in the water.'}
{'title': 'Our Mutual Friend', 'snippet': 'The figures in this boat were those of a strong man with ragged grizzled hair and a sun-browned face, and a dark girl of nineteen or twenty, sufficiently like him to be recognizable as his daughter. The girl rowed, pulling a pair of sculls very easily; the man, with the rudder-lines slack in his hands, and his hands loose in his waistband, kept an eager look out. He had no net, hook, or line, and he could not be a fisherman; his boat had no cushion for a sitter, no paint, no inscription, no appliance beyond a rusty boathook and a coil of rope, and he could not be a waterman; his boat was too crazy and too small to take in cargo for delivery, and he could not be a lighterman or river-carrier; there was no clue to what he looked for, but he looked for something, with a most intent and searching gaze.'}
{'title': 'TO SEA IN A TUB', 'snippet': 'Once a fly alighted on one of the boats, and took quite a long voyage. That made Emma think of trying to find other passengers; and she picked up a great ground beetle, and put him aboard. Poor beetle! he didn\'t want to go, and he wasn\'t used to it. He tumbled about on the deck; the boat tipped under him, and the next thing Emma knew he was overboard. "Oh, he mustn\'t drown!" she cried. "I must get him out!" And she stooped over in great haste to save the poor beetle. But it was a large tub, and a very deep one too; and what did little Emma know about being careful? She lost her balance, and down into the water she went, with a great splash that wrecked all the boats in the same instant. "Mother, mother!" screamed a choking, sputtering voice, as Emma managed to lift her head.'}
{'title': 'The Castaways', 'snippet': 'On drawing near these reefs, Captain Redwood, with the eye of an experienced seaman, saw that while the wind kept up there was no chance for the pinnace to pass them; and to run head on to them would be simply to dash upon destruction. Sail was at once taken in, by letting go the sheet, and dropping the tarpaulin back into the bottom of the boat. The oar that had been set up as a mast was left standing, for there were five others lying idle in the pinnace; and with four of these, Saloo and Murtagh each taking a pair, the boat was manned, the captain himself keeping charge of the tiller. His object was not to approach the land, but to prevent being carried among the breakers, which, surging up snow-white, presented a perilous barrier to their advance. To keep the boat from driving on the dangerous reef, was just as much as the oarsmen could accomplish.'}
{'title': 'Stories of Great Americans for Little Americans', 'snippet': 'After they got the seal, Doctor Kane and his men traveled on. Sometimes they were on the ice. Sometimes they were in the boats. The men were so weak, that they could hardly row the boats. They were so hungry, that they could not sleep well at night. One day they were rowing, when they heard a sound. It came to them across the water. It did not sound like the cry of sea birds. It sounded like people\'s voices. "Listen!" Doctor Kane said to Petersen. Petersen spoke the same language as the people of Greenland. He listened. The sound came again. Petersen was so glad, that he could hardly speak. He told Kane in a half whisper, that it was the voice of some one speaking his own language. It was some Greenland men in a boat. The next day they got to a Greenland town. Then they got into a little ship going to England. They knew that they could get home from England. But the ship stopped at another Greenland town.'}
{'title': '"The Island Queen"', 'snippet': 'Evidently the albatross regarded the boat with curiosity not unmixed with suspicion, for it sailed in wide circles round it, with outstretched neck, head turned on one side, and an eye bent inquiringly downward. By slow degrees the circles diminished, until the giant bird floated almost directly over the boat. Then, apparently, it saw more than enough to satisfy its curiosity, for, uttering a hoarse cry, it swooped aside, and, with a flap of its mighty wings, made off towards the horizon, where it finally disappeared. The flap and the cry seemed, however, to have put life into the little boat, for a human head rose slowly above the gunwale. It was that of a youth, of about twenty years of age, apparently in the last stage of exhaustion. He looked round slowly, with a dazed expression, like one who only half awakes from sleep.'}
{'title': 'THE BULLER-PODINGTON COMPACT', 'snippet': "The reason for this avoidance of each other at their respective rural residences may be briefly stated. Mr. Buller's country house was situated by the sea, and he was very fond of the water. He had a good cat-boat, which he sailed himself with much judgment and skill, and it was his greatest pleasure to take his friends and visitors upon little excursions on the bay. But Mr. Podington was desperately afraid of the water, and he was particularly afraid of any craft sailed by an amateur. If his friend Buller would have employed a professional mariner, of years and experience, to steer and manage his boat, Podington might have been willing to take an occasional sail; but as Buller always insisted upon sailing his own boat, and took it ill if any of his visitors doubted his ability to do so properly, Podington did not wish to wound the self-love of his friend, and he did not wish to be drowned. Consequently he could not bring himself to consent to go to Buller's house by the sea."}
{'title': 'TORPEDO BOATS', 'snippet': 'The torpedo is placed in a tube situated in the fore part of the torpedo boat, and whence it is driven out by means of compressed air. Once fired, it makes its way under the surface to the spot where the shock of its point is to bring about an explosion, and the torpedo boat is thus enabled to operate at a distance and avoid the dangers of an immediate contact with the enemy. Unfortunately this advantage is offset by grave drawbacks; for, in the first place, each of the Whitehead torpedoes costs about ten thousand francs, without counting the expense of obtaining the right to use the patent, and, in the second place, its action is very uncertain, since currents very readily change its direction. However this may be, the inventor has realized a considerable sum by the sale of his secret to the different maritime powers, most of whom have adopted his system. All our ports are provided with flotillas and torpedo boats, and with schools in which the officers and men charged with this service are trained by frequent exercises.'}